# Site settings
title: Ismael Estalayo
email: ismael.em@outlook.com
description: 
# > # this means to ignore newlines until "baseurl:"
# Minimal portfolio.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: ismaelestalayo
github_username:  ismaelestalayo
avatar: /assets/profile1.jpg

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 2
paginate_path: "/blog/page:num/"

host: 0.0.0.0

collections:
  projects:
    output: true
    permalink: /projects/:path/
  blog:
    output: true
    permalink: /blog/:path/

# This will require each of these plugins automatically.
plugins:
  - jekyll-paginate
  - jekyll-redirect-from